bash func: add source_first{,silent}

diff --git a/bash/.config/bash/functions b/bash/.config/bash/functions
--- a/bash/.config/bash/functions
+++ b/bash/.config/bash/functions
@@ -159,7 +159,33 @@ function first_sourceable {
 }
 export_function first_sourceable
 
+# Source the first sourceable argument via source_file
+# Silently return 1 if none are sourceable
+function source_first_silent {
+  local arg
+  for arg; do
+    if [[ -f $arg && -r $arg ]]; then
+      _source_file "$arg"
+      return 0
+    fi
+  done
+  # Nothing matched
+  return 1
+}
+export_function source_first_silent
 
+
+# Source the first sourceable argument via source_file
+# Warn and return 1 if none are sourceable
+function source_first {
+  source_first_silent "$@"
+  if [[ $? -ne 0 ]]; then
+    printf "Couldn't source equivalent of %s\n" "$1" >&2
+    return 1
+  fi
+  return 0
+}
+export_function source_first
 # Copy / rename a function
 # https://stackoverflow.com/a/18839557/5353461
 func_copy() {
